"""
Reconciliation Module Root - Triggers automated state healing and Rust-side alerts.
Coordinates state healer and missed fill detector for comprehensive portfolio integrity.
"""

import asyncio
import logging
from typing import Dict, List, Optional, Any, Callable
from dataclasses import dataclass
import time

from .state_healer import (
    StateHealer, 
    PositionSnapshot, 
    DivergenceEvent,
    DivergenceSeverity,
    get_state_healer
)
from .missed_fill_detector import (
    MissedFillDetector,
    OrderState,
    MissedFill,
    get_missed_fill_detector
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class ReconciliationAlert:
    """Alert generated by reconciliation system."""
    timestamp: float
    alert_type: str  # 'divergence', 'missed_fill', 'sequence_gap', 'critical'
    severity: str
    symbol: str
    description: str
    details: Dict[str, Any]
    action_taken: str
    requires_manual_review: bool
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "symbol": self.symbol,
            "description": self.description,
            "details": self.details,
            "action_taken": self.action_taken,
            "requires_manual_review": self.requires_manual_review
        }


class ReconciliationModule:
    """
    Central module for state reconciliation and healing.
    Coordinates all reconciliation components and manages alerts.
    """
    
    def __init__(self,
                 auto_heal_enabled: bool = True,
                 critical_alert_callback: Optional[Callable] = None,
                 rust_ipc_channel: Optional[Any] = None):
        """
        Initialize reconciliation module.
        
        Args:
            auto_heal_enabled: Whether to automatically heal divergences
            critical_alert_callback: Callback for critical alerts
            rust_ipc_channel: Channel for sending alerts to Rust side
        """
        self.auto_heal_enabled = auto_heal_enabled
        self.critical_alert_callback = critical_alert_callback
        self.rust_ipc_channel = rust_ipc_channel
        
        # Initialize components
        self.state_healer = get_state_healer()
        self.missed_fill_detector = get_missed_fill_detector()
        
        # Alert management
        self._alerts: List[ReconciliationAlert] = []
        self._alert_callbacks: List[Callable] = []
        
        # Background tasks
        self._reconciliation_task: Optional[asyncio.Task] = None
        self._is_running = False
        
        # Statistics
        self._total_alerts = 0
        self._critical_alerts = 0
        self._auto_heals_performed = 0
    
    def update_position_snapshot(self, snapshot: PositionSnapshot):
        """Update position snapshot from a source."""
        self.state_healer.update_snapshot(snapshot)
    
    def track_order(self, order: OrderState):
        """Start tracking an order for missed fill detection."""
        self.missed_fill_detector.track_order(order)
    
    def process_execution_report(self, order_id: str, fill_qty: float,
                                  fill_price: float, sequence: int,
                                  timestamp: float, symbol: str):
        """Process execution report from WebSocket."""
        self.missed_fill_detector.process_execution_report(
            order_id, fill_qty, fill_price, sequence, timestamp, symbol
        )
    
    async def run_reconciliation_loop(self, stop_event: asyncio.Event):
        """Run the main reconciliation loop."""
        self._is_running = True
        logger.info("Starting reconciliation module")
        
        while not stop_event.is_set():
            try:
                # Check for state divergence
                divergences = self.state_healer.check_divergence()
                
                for div in divergences:
                    await self._handle_divergence(div)
                
                # Check for stale orders
                current_time = time.time()
                stale_fills = self.missed_fill_detector.detect_stale_orders(current_time)
                
                for mf in stale_fills:
                    await self._handle_missed_fill(mf)
                
                await asyncio.sleep(1.0)  # Check every second
                
            except Exception as e:
                logger.error(f"Reconciliation loop error: {e}")
                await asyncio.sleep(1.0)
        
        self._is_running = False
        logger.info("Reconciliation module stopped")
    
    async def _handle_divergence(self, event: DivergenceEvent):
        """Handle a detected divergence."""
        severity_str = event.severity.value
        requires_review = event.severity in [DivergenceSeverity.HIGH, DivergenceSeverity.CRITICAL]
        
        action_taken = "none"
        if self.auto_heal_enabled and event.auto_corrected:
            action_taken = event.correction_action
            self._auto_heals_performed += 1
        
        alert = ReconciliationAlert(
            timestamp=event.timestamp,
            alert_type="divergence",
            severity=severity_str,
            symbol=event.symbol,
            description=f"Divergence in {event.field}: {event.difference_pct:.2f}%",
            details=event.to_dict(),
            action_taken=action_taken,
            requires_manual_review=requires_review
        )
        
        await self._send_alert(alert)
        
        # Send to Rust side for critical divergences
        if event.severity == DivergenceSeverity.CRITICAL and self.rust_ipc_channel:
            await self._send_rust_alert(alert)
    
    async def _handle_missed_fill(self, missed_fill: MissedFill):
        """Handle a detected missed fill."""
        alert = ReconciliationAlert(
            timestamp=missed_fill.detection_time,
            alert_type="missed_fill",
            severity="high" if missed_fill.confidence > 0.8 else "medium",
            symbol=missed_fill.symbol,
            description=f"Missed fill detected: qty={missed_fill.estimated_qty}",
            details=missed_fill.to_dict(),
            action_taken="state_updated" if missed_fill.confidence > 0.8 else "flagged",
            requires_manual_review=missed_fill.confidence < 0.5
        )
        
        await self._send_alert(alert)
    
    async def _send_alert(self, alert: ReconciliationAlert):
        """Send alert to all registered callbacks."""
        self._alerts.append(alert)
        self._total_alerts += 1
        
        if alert.severity == "critical":
            self._critical_alerts += 1
        
        # Limit alert history
        if len(self._alerts) > 1000:
            self._alerts.pop(0)
        
        # Call registered callbacks
        for callback in self._alert_callbacks:
            try:
                if asyncio.iscoroutinefunction(callback):
                    await callback(alert)
                else:
                    callback(alert)
            except Exception as e:
                logger.error(f"Alert callback error: {e}")
        
        # Critical alert callback
        if alert.severity == "critical" and self.critical_alert_callback:
            try:
                self.critical_alert_callback(alert)
            except Exception as e:
                logger.error(f"Critical alert callback error: {e}")
        
        logger.warning(
            f"Alert [{alert.severity}]: {alert.alert_type} on {alert.symbol} - {alert.description}"
        )
    
    async def _send_rust_alert(self, alert: ReconciliationAlert):
        """Send alert to Rust side via IPC."""
        if not self.rust_ipc_channel:
            return
        
        try:
            # Would send via actual IPC mechanism
            logger.info(f"Sending Rust alert: {alert.alert_type} on {alert.symbol}")
            # Example: await self.rust_ipc_channel.send(alert.to_dict())
        except Exception as e:
            logger.error(f"Failed to send Rust alert: {e}")
    
    def register_alert_callback(self, callback: Callable):
        """Register a callback for alerts."""
        self._alert_callbacks.append(callback)
        logger.info(f"Registered alert callback: {callback.__name__}")
    
    def request_rest_reconciliation(self, rest_snapshots: Dict[str, Dict[str, Any]]):
        """Request reconciliation with exchange REST API."""
        missed = self.missed_fill_detector.reconcile_with_rest(rest_snapshots)
        
        for mf in missed:
            asyncio.create_task(self._handle_missed_fill(mf))
        
        return len(missed)
    
    def get_active_divergences(self) -> List[Dict[str, Any]]:
        """Get recent divergence events."""
        summary = self.state_healer.get_divergence_summary()
        return summary.get("recent_events", [])
    
    def get_missed_fills(self) -> List[Dict[str, Any]]:
        """Get detected missed fills."""
        return self.missed_fill_detector.get_missed_fills()
    
    def get_module_stats(self) -> Dict[str, Any]:
        """Get module statistics."""
        return {
            "total_alerts": self._total_alerts,
            "critical_alerts": self._critical_alerts,
            "auto_heals_performed": self._auto_heals_performed,
            "alerts_history_size": len(self._alerts),
            "state_healer_stats": self.state_healer.get_divergence_summary(),
            "missed_fill_stats": self.missed_fill_detector.get_detector_stats(),
            "is_running": self._is_running
        }
    
    def health_check(self) -> Dict[str, Any]:
        """Return module health status."""
        return {
            "running": self._is_running,
            "auto_heal_enabled": self.auto_heal_enabled,
            "state_healer": self.state_healer.health_check(),
            "missed_fill_detector": self.missed_fill_detector.health_check(),
            "pending_alerts": len([a for a in self._alerts if a.requires_manual_review]),
            "rust_ipc_connected": self.rust_ipc_channel is not None
        }
    
    def enable_auto_heal(self, enabled: bool = True):
        """Enable or disable auto-healing."""
        self.auto_heal_enabled = enabled
        self.state_healer.enable_auto_correction(enabled)
        logger.info(f"Auto-heal {'enabled' if enabled else 'disabled'}")


# Module singleton
_rec_module: Optional[ReconciliationModule] = None


def get_reconciliation_module(**kwargs) -> ReconciliationModule:
    """Get or create the global reconciliation module."""
    global _rec_module
    
    if _rec_module is None:
        _rec_module = ReconciliationModule(**kwargs)
        logger.info("Created reconciliation module")
    
    return _rec_module


async def initialize_reconciliation(rust_ipc_channel: Optional[Any] = None,
                                     critical_callback: Optional[Callable] = None) -> ReconciliationModule:
    """Initialize and start the reconciliation module."""
    module = get_reconciliation_module(
        rust_ipc_channel=rust_ipc_channel,
        critical_alert_callback=critical_callback
    )
    
    stop_event = asyncio.Event()
    module._reconciliation_task = asyncio.create_task(
        module.run_reconciliation_loop(stop_event)
    )
    
    return module


if __name__ == "__main__":
    # Test the reconciliation module
    print("Testing Reconciliation Module...")
    
    module = ReconciliationModule(auto_heal_enabled=True)
    
    # Create test snapshots
    base_time = time.time()
    
    # Normal snapshots - all agree
    module.update_position_snapshot(PositionSnapshot(
        timestamp=base_time,
        source='nautilus',
        symbol='BTC/USD',
        net_position=100.0,
        long_qty=100.0,
        short_qty=0.0,
        avg_entry_price=45000.0,
        unrealized_pnl=500.0,
        realized_pnl=1000.0
    ))
    
    module.update_position_snapshot(PositionSnapshot(
        timestamp=base_time,
        source='exchange_rest',
        symbol='BTC/USD',
        net_position=100.0,
        long_qty=100.0,
        short_qty=0.0,
        avg_entry_price=45000.0,
        unrealized_pnl=500.0,
        realized_pnl=1000.0
    ))
    
    # Check - should be no divergence
    print(f"\nInitial check: {module.get_module_stats()}")
    
    # Introduce divergence
    module.update_position_snapshot(PositionSnapshot(
        timestamp=base_time,
        source='nautilus',
        symbol='BTC/USD',
        net_position=110.0,  # Different!
        long_qty=110.0,
        short_qty=0.0,
        avg_entry_price=45000.0,
        unrealized_pnl=500.0,
        realized_pnl=1000.0
    ))
    
    # Trigger check
    divergences = module.state_healer.check_divergence()
    print(f"\nAfter introducing divergence: {len(divergences)} events")
    
    # Test missed fill detection
    order = OrderState(
        order_id="ord_456",
        client_order_id="client_456",
        symbol='ETH/USD',
        side='buy',
        order_type='limit',
        quantity=5.0,
        price=3000.0
    )
    
    module.track_order(order)
    
    # Simulate REST finding discrepancy
    rest_snapshot = {
        "ord_456": {
            "filled_qty": 5.0,  # Fully filled but we don't know
            "avg_fill_price": 3000.0,
            "sequence": 50,
            "last_fill_time": base_time
        }
    }
    
    missed_count = module.request_rest_reconciliation(rest_snapshot)
    print(f"\nREST reconciliation found {missed_count} missed fills")
    
    print(f"\nFinal Stats: {module.get_module_stats()}")
    print(f"Health: {module.health_check()}")
