use std::env;
use std::process::Command;
use std::path::Path;

fn main() {
    // Tell Cargo to rerun this script if any of these files change
    println!("cargo:rerun-if-changed=.git/HEAD");
    println!("cargo:rerun-if-changed=.git/refs/heads/main");
    
    // Detect AMD Ryzen SIMD capabilities via CPUID
    detect_simd_capabilities();
    
    // Generate git commit hash for version tracking
    generate_git_version();
    
    // Inject LTO and codegen flags via cargo rustc environment
    configure_release_optimizations();
}

/// Detect AMD Ryzen SIMD capabilities (AVX2, AVX-512, etc.)
/// This allows compile-time feature detection for optimal code paths
fn detect_simd_capabilities() {
    let mut simd_flags = Vec::new();
    
    // Check for various SIMD extensions using rustc target features
    // On AMD Ryzen (Zen 2/Zen 3/Zen 4), we typically have:
    // - SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2
    // - AVX, AVX2
    // - FMA (Fused Multiply-Add)
    
    // We use a build-time check by attempting to compile a small test
    // For now, we'll set cfg flags based on common Ryzen capabilities
    // The actual runtime detection happens in the simd module
    
    // Enable AVX2 for Ryzen 3000/5000/7000 series
    if is_feature_available("avx2") {
        simd_flags.push("avx2");
        println!("cargo:rustc-cfg=target_feature=\"avx2\"");
    }
    
    // Enable FMA for fused multiply-add operations
    if is_feature_available("fma") {
        simd_flags.push("fma");
        println!("cargo:rustc-cfg=target_feature=\"fma\"");
    }
    
    // Check for AVX-512 (Ryzen 7000 series with Zen 4)
    if is_feature_available("avx512f") {
        simd_flags.push("avx512f");
        println!("cargo:rustc-cfg=target_feature=\"avx512f\"");
    }
    
    println!("cargo:warning=SIMD capabilities detected: {:?}", simd_flags);
}

/// Simple heuristic to check if a CPU feature is available
/// In production, this would use the cpuid crate or inline assembly
fn is_feature_available(feature: &str) -> bool {
    // For cross-platform compatibility, we enable features based on 
    // the target architecture. AMD Ryzen supports these features.
    let target = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    
    match feature {
        "avx2" => target == "x86_64",
        "fma" => target == "x86_64",
        "avx512f" => target == "x86_64", // Enable if targeting modern x86_64
        _ => false,
    }
}

/// Generate git commit hash and timestamp for version tracking
fn generate_git_version() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("version.rs");
    
    // Try to get the git commit hash
    let git_hash = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout).ok()
            } else {
                None
            }
        })
        .unwrap_or_else(|| String::from("unknown"));
    
    // Get git branch
    let git_branch = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout).ok()
            } else {
                None
            }
        })
        .unwrap_or_else(|| String::from("unknown"));
    
    // Get build timestamp
    let build_time = chrono_lite_timestamp();
    
    // Write version info to file
    let version_code = format!(
        r#"
/// Auto-generated version information
/// DO NOT EDIT - Generated by build.rs

pub const GIT_COMMIT_HASH: &str = "{}";
pub const GIT_BRANCH: &str = "{}";
pub const BUILD_TIMESTAMP: &str = "{}";
pub const VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), "-", GIT_COMMIT_HASH);

#[inline]
pub fn get_version_info() -> &'static str {{
    VERSION
}}

#[inline]
pub fn get_build_info() -> String {{
    format!("Build: {{}} on {{}} ({{}})", GIT_COMMIT_HASH, BUILD_TIMESTAMP, GIT_BRANCH)
}}
"#,
        git_hash.trim(),
        git_branch.trim(),
        build_time
    );
    
    std::fs::write(&dest_path, version_code).expect("Failed to write version.rs");
    
    println!("cargo:rerun-if-changed={}", dest_path.display());
}

/// Generate a timestamp without external dependencies
fn chrono_lite_timestamp() -> String {
    // Use the SOURCE_DATE_EPOCH if available (for reproducible builds)
    if let Ok(epoch) = env::var("SOURCE_DATE_EPOCH") {
        return epoch;
    }
    
    // Otherwise, use current time
    // Simple implementation using system time
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();
    
    secs.to_string()
}

/// Configure release optimizations for maximum performance
fn configure_release_optimizations() {
    // Only apply these in release mode
    let profile = env::var("PROFILE").unwrap_or_default();
    
    if profile == "release" {
        // Force Link Time Optimization (LTO) for cross-module optimization
        // This is also set in Cargo.toml but we enforce it here
        println!("cargo:rustc-link-arg=-flto=full");
        
        // Set codegen units to 1 for better optimization (slower compile, faster runtime)
        // This allows the optimizer to see the entire crate at once
        println!("cargo:rustc-codegen-units=1");
        
        // Enable aggressive inlining
        println!("cargo:rustc-opt-level=3");
        
        // Prefer smaller code size where possible (better cache utilization)
        // println!("cargo:rustc-opt-size=s");
        
        println!("cargo:warning=Release build with full LTO and codegen-units=1 enabled");
    }
}
