//! Brinson-Fachler Performance Attribution Model
//! 
//! Quantifies PnL generated by asset selection vs portfolio weighting (Allocation, Selection, Interaction effects).
//! Feeds data to SOUL.md for self-learning optimization.

use std::sync::atomic::{AtomicU64, AtomicI64, Ordering};

/// Maximum number of assets in the portfolio
pub const MAX_ASSETS: usize = 64;

/// Maximum attribution periods stored
pub const MAX_PERIODS: usize = 256;

/// Attribution effect components
#[derive(Debug, Clone)]
pub struct AttributionEffects {
    pub allocation_effect: f64,   // PnL from overweighting/underweighting sectors
    pub selection_effect: f64,    // PnL from security selection within sectors
    pub interaction_effect: f64,  // Combined effect of allocation and selection
    pub total_active_return: f64, // Sum of all effects
}

/// Single period attribution result
#[derive(Debug, Clone)]
pub struct PeriodAttribution {
    pub period_id: u64,
    pub benchmark_return: f64,
    pub portfolio_return: f64,
    pub active_return: f64,
    pub effects: AttributionEffects,
    pub timestamp_ns: u64,
}

/// Asset-level attribution breakdown
#[derive(Debug, Clone)]
pub struct AssetAttribution {
    pub asset_id: u32,
    pub weight: f64,              // Portfolio weight
    pub benchmark_weight: f64,    // Benchmark weight
    pub asset_return: f64,        // Asset return
    pub benchmark_return: f64,    // Benchmark asset return
    pub contribution: f64,        // Return contribution
    pub allocation_contrib: f64,  // Allocation contribution
    pub selection_contrib: f64,   // Selection contribution
    pub interaction_contrib: f64, // Interaction contribution
}

/// Brinson-Fachler attribution engine
pub struct BrinsonAttributor {
    /// Portfolio weights (Q16.48 fixed-point)
    portfolio_weights: [AtomicI64; MAX_ASSETS],
    /// Benchmark weights (Q16.48 fixed-point)
    benchmark_weights: [AtomicI64; MAX_ASSETS],
    /// Asset returns (Q16.48 fixed-point)
    asset_returns: [AtomicI64; MAX_ASSETS],
    /// Benchmark asset returns (Q16.48 fixed-point)
    benchmark_asset_returns: [AtomicI64; MAX_ASSETS],
    /// Active asset count
    asset_count: AtomicU64,
    /// Attribution history (ring buffer)
    history: [Option<PeriodAttribution>; MAX_PERIODS],
    /// History head pointer
    history_head: AtomicU64,
    /// Period counter
    period_count: AtomicU64,
    /// Total benchmark return (Q16.48)
    total_benchmark_return: AtomicI64,
}

impl BrinsonAttributor {
    pub const fn new() -> Self {
        Self {
            portfolio_weights: [AtomicI64::new(0); MAX_ASSETS],
            benchmark_weights: [AtomicI64::new(0); MAX_ASSETS],
            asset_returns: [AtomicI64::new(0); MAX_ASSETS],
            benchmark_asset_returns: [AtomicI64::new(0); MAX_ASSETS],
            asset_count: AtomicU64::new(0),
            history: [None; MAX_PERIODS],
            history_head: AtomicU64::new(0),
            period_count: AtomicU64::new(0),
            total_benchmark_return: AtomicI64::new(0),
        }
    }
    
    /// Set portfolio weight for an asset
    #[inline]
    pub fn set_portfolio_weight(&self, asset_idx: usize, weight: f64) {
        if asset_idx < MAX_ASSETS {
            let fixed = (weight * (1u64 << 48) as f64) as i64;
            self.portfolio_weights[asset_idx].store(fixed, Ordering::Release);
        }
    }
    
    /// Set benchmark weight for an asset
    #[inline]
    pub fn set_benchmark_weight(&self, asset_idx: usize, weight: f64) {
        if asset_idx < MAX_ASSETS {
            let fixed = (weight * (1u64 << 48) as f64) as i64;
            self.benchmark_weights[asset_idx].store(fixed, Ordering::Release);
        }
    }
    
    /// Set asset return
    #[inline]
    pub fn set_asset_return(&self, asset_idx: usize, return_pct: f64) {
        if asset_idx < MAX_ASSETS {
            let fixed = (return_pct * (1u64 << 48) as f64) as i64;
            self.asset_returns[asset_idx].store(fixed, Ordering::Release);
        }
    }
    
    /// Set benchmark asset return
    #[inline]
    pub fn set_benchmark_asset_return(&self, asset_idx: usize, return_pct: f64) {
        if asset_idx < MAX_ASSETS {
            let fixed = (return_pct * (1u64 << 48) as f64) as i64;
            self.benchmark_asset_returns[asset_idx].store(fixed, Ordering::Release);
        }
    }
    
    /// Set active asset count
    #[inline]
    pub fn set_asset_count(&self, count: usize) {
        self.asset_count.store(count.min(MAX_ASSETS) as u64, Ordering::Release);
    }
    
    /// Compute Brinson-Fachler attribution for current period
    pub fn compute_attribution(&self) -> PeriodAttribution {
        let asset_count = self.asset_count.load(Ordering::Acquire) as usize;
        let period_id = self.period_count.load(Ordering::Acquire);
        
        // Calculate portfolio and benchmark returns
        let mut portfolio_return = 0.0f64;
        let mut benchmark_return = 0.0f64;
        
        // Asset-level attributions
        let mut asset_attributions: [AssetAttribution; MAX_ASSETS] = [
            AssetAttribution {
                asset_id: 0,
                weight: 0.0,
                benchmark_weight: 0.0,
                asset_return: 0.0,
                benchmark_return: 0.0,
                contribution: 0.0,
                allocation_contrib: 0.0,
                selection_contrib: 0.0,
                interaction_contrib: 0.0,
            }; MAX_ASSETS
        ];
        
        // Brinson-Fachler decomposition:
        // Allocation = (wp - wb) * (rb_sector - rb_total)
        // Selection = wb * (rp_sector - rb_sector)
        // Interaction = (wp - wb) * (rp_sector - rb_sector)
        
        for i in 0..asset_count {
            let wp = self.portfolio_weights[i].load(Ordering::Acquire) as f64 / (1u64 << 48) as f64;
            let wb = self.benchmark_weights[i].load(Ordering::Acquire) as f64 / (1u64 << 48) as f64;
            let rp = self.asset_returns[i].load(Ordering::Acquire) as f64 / (1u64 << 48) as f64;
            let rb = self.benchmark_asset_returns[i].load(Ordering::Acquire) as f64 / (1u64 << 48) as f64;
            
            portfolio_return += wp * rp;
            benchmark_return += wb * rb;
            
            asset_attributions[i] = AssetAttribution {
                asset_id: i as u32,
                weight: wp,
                benchmark_weight: wb,
                asset_return: rp,
                benchmark_return: rb,
                contribution: wp * rp,
                allocation_contrib: 0.0,  // Calculated below
                selection_contrib: 0.0,
                interaction_contrib: 0.0,
            };
        }
        
        // Calculate allocation, selection, and interaction effects
        let mut total_allocation = 0.0f64;
        let mut total_selection = 0.0f64;
        let mut total_interaction = 0.0f64;
        
        for i in 0..asset_count {
            let wp = asset_attributions[i].weight;
            let wb = asset_attributions[i].benchmark_weight;
            let rp = asset_attributions[i].asset_return;
            let rb = asset_attributions[i].benchmark_return;
            
            // Brinson-Fachler components
            let allocation = (wp - wb) * (rb - benchmark_return);
            let selection = wb * (rp - rb);
            let interaction = (wp - wb) * (rp - rb);
            
            asset_attributions[i].allocation_contrib = allocation;
            asset_attributions[i].selection_contrib = selection;
            asset_attributions[i].interaction_contrib = interaction;
            
            total_allocation += allocation;
            total_selection += selection;
            total_interaction += interaction;
        }
        
        let active_return = portfolio_return - benchmark_return;
        
        let effects = AttributionEffects {
            allocation_effect: total_allocation,
            selection_effect: total_selection,
            interaction_effect: total_interaction,
            total_active_return: total_allocation + total_selection + total_interaction,
        };
        
        let result = PeriodAttribution {
            period_id,
            benchmark_return,
            portfolio_return,
            active_return,
            effects,
            timestamp_ns: get_timestamp_ns(),
        };
        
        // Store in history
        self.store_attribution(result.clone());
        
        // Update period count
        self.period_count.fetch_add(1, Ordering::Release);
        
        result
    }
    
    /// Store attribution result in ring buffer
    fn store_attribution(&self, attr: PeriodAttribution) {
        let head = self.history_head.load(Ordering::Acquire);
        let idx = (head % MAX_PERIODS as u64) as usize;
        
        // Safety: This is single-writer, so no lock needed
        unsafe {
            let history_ptr = &self.history as *const [Option<PeriodAttribution>; MAX_PERIODS]
                as *mut [Option<PeriodAttribution>; MAX_PERIODS];
            (*history_ptr)[idx] = Some(attr);
        }
        
        self.history_head.store(head + 1, Ordering::Release);
    }
    
    /// Get average allocation effect over history
    pub fn avg_allocation_effect(&self) -> f64 {
        self.avg_effect(|a| a.effects.allocation_effect)
    }
    
    /// Get average selection effect over history
    pub fn avg_selection_effect(&self) -> f64 {
        self.avg_effect(|a| a.effects.selection_effect)
    }
    
    /// Get average interaction effect over history
    pub fn avg_interaction_effect(&self) -> f64 {
        self.avg_effect(|a| a.effects.interaction_effect)
    }
    
    /// Generic average effect calculator
    fn avg_effect<F>(&self, selector: F) -> f64
    where
        F: Fn(&PeriodAttribution) -> f64,
    {
        let head = self.history_head.load(Ordering::Acquire);
        let count = head.min(MAX_PERIODS as u64);
        
        if count == 0 {
            return 0.0;
        }
        
        let mut sum = 0.0f64;
        for i in 0..count as usize {
            if let Some(ref attr) = self.history[i] {
                sum += selector(attr);
            }
        }
        
        sum / count as f64
    }
    
    /// Get information ratio of active returns
    pub fn information_ratio(&self) -> f64 {
        let head = self.history_head.load(Ordering::Acquire);
        let count = head.min(MAX_PERIODS as u64);
        
        if count < 2 {
            return 0.0;
        }
        
        // Calculate mean active return
        let mut sum = 0.0f64;
        let mut valid_count = 0u64;
        for i in 0..count as usize {
            if let Some(ref attr) = self.history[i] {
                sum += attr.active_return;
                valid_count += 1;
            }
        }
        
        if valid_count < 2 {
            return 0.0;
        }
        
        let mean = sum / valid_count as f64;
        
        // Calculate standard deviation
        let mut var_sum = 0.0f64;
        for i in 0..count as usize {
            if let Some(ref attr) = self.history[i] {
                let diff = attr.active_return - mean;
                var_sum += diff * diff;
            }
        }
        
        let std = (var_sum / (valid_count - 1) as f64).sqrt();
        
        if std < 1e-10 {
            return 0.0;
        }
        
        mean / std
    }
    
    /// Get latest attribution result
    pub fn latest_attribution(&self) -> Option<PeriodAttribution> {
        let head = self.history_head.load(Ordering::Acquire);
        if head == 0 {
            return None;
        }
        let idx = ((head - 1) % MAX_PERIODS as u64) as usize;
        self.history[idx].clone()
    }
    
    /// Reset attribution state
    pub fn reset(&self) {
        for i in 0..MAX_ASSETS {
            self.portfolio_weights[i].store(0, Ordering::Release);
            self.benchmark_weights[i].store(0, Ordering::Release);
            self.asset_returns[i].store(0, Ordering::Release);
            self.benchmark_asset_returns[i].store(0, Ordering::Release);
        }
        self.asset_count.store(0, Ordering::Release);
        self.period_count.store(0, Ordering::Release);
        self.history_head.store(0, Ordering::Release);
    }
}

/// Get current timestamp in nanoseconds
#[inline]
fn get_timestamp_ns() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos() as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_brinson_attribution() {
        let attr = BrinsonAttributor::new();
        
        // Setup 3-asset portfolio
        attr.set_asset_count(3);
        
        // Portfolio: Overweight asset 0, underweight asset 2
        attr.set_portfolio_weight(0, 0.5);  // 50%
        attr.set_portfolio_weight(1, 0.3);  // 30%
        attr.set_portfolio_weight(2, 0.2);  // 20%
        
        // Benchmark: Equal weight
        attr.set_benchmark_weight(0, 0.333);
        attr.set_benchmark_weight(1, 0.333);
        attr.set_benchmark_weight(2, 0.334);
        
        // Returns: Asset 0 outperforms, asset 2 underperforms
        attr.set_asset_return(0, 0.10);     // 10%
        attr.set_asset_return(1, 0.05);     // 5%
        attr.set_asset_return(2, -0.02);    // -2%
        
        attr.set_benchmark_asset_return(0, 0.08);
        attr.set_benchmark_asset_return(1, 0.05);
        attr.set_benchmark_asset_return(2, 0.02);
        
        // Compute attribution
        let result = attr.compute_attribution();
        
        // Verify results
        assert!(result.portfolio_return > result.benchmark_return);
        assert!(result.active_return > 0.0);
        assert!(result.effects.total_active_return.abs() - result.active_return.abs() < 0.01);
    }
    
    #[test]
    fn test_information_ratio() {
        let attr = BrinsonAttributor::new();
        attr.set_asset_count(2);
        
        // Simulate multiple periods with positive alpha
        for i in 0..20 {
            attr.set_portfolio_weight(0, 0.6);
            attr.set_portfolio_weight(1, 0.4);
            attr.set_benchmark_weight(0, 0.5);
            attr.set_benchmark_weight(1, 0.5);
            
            // Consistent outperformance
            attr.set_asset_return(0, 0.02 + (i as f64 * 0.001));
            attr.set_asset_return(1, 0.01);
            attr.set_benchmark_asset_return(0, 0.015);
            attr.set_benchmark_asset_return(1, 0.01);
            
            attr.compute_attribution();
        }
        
        let ir = attr.information_ratio();
        assert!(ir > 0.5); // Should have positive IR with consistent alpha
    }
}
