#!/bin/bash
# =============================================================================
# HFT Crypto Bot - System Hardening Script
# =============================================================================
# Applies aggressive sysctl tweaks for:
# - TCP buffer tuning for low-latency networking
# - IPv6 disable (if not needed)
# - File descriptor optimization
# - Memory management for trading workloads
# =============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

# =============================================================================
# Apply sysctl Configuration
# =============================================================================
apply_sysctl() {
    local sysctl_file="/etc/sysctl.d/99-hft-crypto-bot.conf"
    
    log_info "Creating sysctl configuration at ${sysctl_file}..."
    
    cat > "${sysctl_file}" << 'EOF'
# =============================================================================
# HFT Crypto Bot - Aggressive Kernel Tuning
# =============================================================================
# Generated by security/harden.sh
# Apply with: sysctl --system
# =============================================================================

# -----------------------------------------------------------------------------
# NETWORK STACK OPTIMIZATION
# -----------------------------------------------------------------------------

# Maximum socket receive/send buffer sizes (128MB each)
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728

# Default socket buffer sizes (16MB each)
net.core.rmem_default = 16777216
net.core.wmem_default = 16777216

# Socket option memory limits
net.core.optmem_max = 524288

# Network device backlog (packets queued before dropping)
net.core.netdev_max_backlog = 262144

# Connection queue sizes (SYN backlog and accept queue)
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 65536
net.ipv4.tcp_abort_on_overflow = 1

# TCP Fast Open (reduce connection latency by 1 RTT)
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_fastopen_blackhole_detect_sec = 3600

# Congestion control - BBR for lowest latency
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# Reduce TCP latency
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1

# TCP timestamps disabled (saves 12 bytes per packet, minor latency gain)
net.ipv4.tcp_timestamps = 0

# TCP window scaling enabled
net.ipv4.tcp_window_scaling = 1

# Disable slow start after idle
net.ipv4.tcp_slow_start_after_idle = 0

# Maximum number of sockets in TIME_WAIT state
net.ipv4.tcp_max_tw_buckets = 1440000

# Reuse TIME_WAIT sockets for new connections
net.ipv4.tcp_tw_reuse = 1

# Keepalive settings (aggressive detection of dead peers)
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# Ephemeral port range (maximize available ports)
net.ipv4.ip_local_port_range = 1024 65535

# IP forwarding (disabled for security unless needed)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# ICMP rate limiting (prevent ping floods)
net.ipv4.icmp_ratelimit = 100
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Reverse path filtering (anti-spoofing)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 3

# FIN timeout reduction
net.ipv4.tcp_fin_timeout = 15

# MTU discovery
net.ipv4.tcp_mtu_probing = 1

# SACK (Selective Acknowledgment) for better loss recovery
net.ipv4.tcp_sack = 1
net.ipv4.tcp_dsack = 1

# F-RTO (Forward RTO Recovery)
net.ipv4.tcp_frto = 2

# Proportional Rate Reduction
net.ipv4.tcp_pacing_ss_ratio = 200
net.ipv4.tcp_pacing_ca_ratio = 120

# -----------------------------------------------------------------------------
# IPv6 DISABLE (Optional - uncomment if IPv6 is not needed)
# -----------------------------------------------------------------------------

# Disable IPv6 entirely
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

# -----------------------------------------------------------------------------
# MEMORY MANAGEMENT
# -----------------------------------------------------------------------------

# Swappiness - avoid swapping at all costs (critical for HFT)
vm.swappiness = 1

# Overcommit memory strategy (allow aggressive allocation)
vm.overcommit_memory = 1

# Dirty page writeback tuning (balance between latency and throughput)
vm.dirty_ratio = 10
vm.dirty_background_ratio = 5
vm.dirty_expire_centisecs = 3000
vm.dirty_writeback_centisecs = 500

# Virtual memory area limit (for large allocations)
vm.max_map_count = 262144

# Disable NUMA balancing (we handle pinning manually)
kernel.numa_balancing = 0

# Transparent hugepages - use madvise for database-like workloads
# (set via /sys/kernel/mm/transparent_hugepage/enabled instead)

# OOM killer tuning (prefer killing non-essential processes first)
vm.oom_kill_allocating_task = 0
vm.panic_on_oom = 0

# Memory compaction (reduce fragmentation)
vm.compact_unevictable_allowed = 1

# Zone reclaim (disable for NUMA systems with manual pinning)
vm.zone_reclaim_mode = 0

# -----------------------------------------------------------------------------
# FILE SYSTEM
# -----------------------------------------------------------------------------

# Maximum file handles system-wide
fs.file-max = 2097152

# Inotify watches (for file monitoring)
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 512

# Asynchronous I/O limits
fs.aio-max-nr = 1048576

# Pipe buffer size
fs.pipe-max-size = 1048576

# -----------------------------------------------------------------------------
# KERNEL SCHEDULING
# -----------------------------------------------------------------------------

# Real-time scheduling budget (95% of time slice for RT tasks)
kernel.sched_rt_runtime_us = 950000
kernel.sched_rt_period_us = 1000000

# Energy performance bias (prefer performance over power savings)
kernel.energy_perf_bias = 0

# Watchdog threshold (increase to prevent false positives under load)
kernel.watchdog_thresh = 15

# Softlockup detection
kernel.softlockup_all_cpu_backtrace = 1
kernel.softlockup_panic = 0

# Hardlockup detection
kernel.hardlockup_panic = 1

# Panic on OOM (optional - set to 1 for automatic reboot on OOM)
kernel.panic_on_oops = 1

# Core dump pattern (disable core dumps in production)
kernel.core_pattern = |/bin/false

# -----------------------------------------------------------------------------
# SECURITY HARDENING
# -----------------------------------------------------------------------------

# Restrict dmesg access (hide kernel messages from unprivileged users)
kernel.dmesg_restrict = 1

# Restrict kernel pointers (ASLR enhancement)
kernel.kptr_restrict = 2

# Unprivileged user namespaces (disable if not needed)
user.max_user_namespaces = 0

# Perf event restrictions (prevent side-channel attacks)
kernel.perf_event_paranoid = 3

# BPF JIT hardening
net.core.bpf_jit_harden = 2

EOF
    
    # Apply the sysctl settings
    log_info "Applying sysctl settings..."
    sysctl --system --quiet
    
    log_success "Sysctl configuration applied successfully"
}

# =============================================================================
# Configure Network Interface
# =============================================================================
configure_network_interface() {
    log_info "Configuring network interface optimizations..."
    
    # Find primary network interface (excluding lo)
    local iface=$(ip route | grep default | awk '{print $5}' | head -1)
    
    if [[ -z "${iface}" ]]; then
        log_warning "Could not determine primary network interface"
        return
    fi
    
    log_info "Configuring interface: ${iface}"
    
    # Increase ring buffer sizes
    ethtool -G "${iface}" rx 4096 tx 4096 2>/dev/null || true
    
    # Enable interrupt coalescing (adjust based on NIC)
    ethtool -C "${iface}" adaptive-rx on adaptive-tx off 2>/dev/null || true
    
    # Offload features (enable most for throughput)
    ethtool -K "${iface}" gro on gso on tso on lro on 2>/dev/null || true
    
    # Set interrupt affinity (optional - requires irqbalance disabled)
    # This would be done per-IRQ based on /proc/interrupts
    
    log_success "Network interface configured"
}

# =============================================================================
# Configure IRQ Affinity
# =============================================================================
configure_irq_affinity() {
    log_info "Configuring IRQ affinity for network cards..."
    
    # This is a simplified version - production should be more sophisticated
    # Bind network IRQs to specific CPUs (typically system cores, not trading cores)
    
    local system_cores="0,1"  # Adjust based on your isolcpus configuration
    
    # Find network card IRQs
    for irq in $(grep -l "eth\|ens\|enp" /proc/interrupts | cut -d: -f1); do
        echo "${system_cores}" > /proc/irq/${irq}/smp_affinity_list 2>/dev/null || true
    done
    
    log_success "IRQ affinity configured"
}

# =============================================================================
# Verify Configuration
# =============================================================================
verify_configuration() {
    log_info "Verifying configuration..."
    
    local errors=0
    
    # Check key sysctl values
    local checks=(
        "net.ipv4.tcp_fastopen:3"
        "net.ipv4.tcp_low_latency:1"
        "vm.swappiness:1"
        "net.core.rmem_max:134217728"
        "net.core.wmem_max:134217728"
    )
    
    for check in "${checks[@]}"; do
        local key="${check%%:*}"
        local expected="${check##*:}"
        local actual=$(sysctl -n "${key}" 2>/dev/null || echo "N/A")
        
        if [[ "${actual}" == "${expected}" ]]; then
            log_success "${key} = ${actual}"
        else
            log_warning "${key} = ${actual} (expected: ${expected})"
            ((errors++)) || true
        fi
    done
    
    if [[ ${errors} -gt 0 ]]; then
        log_warning "${errors} configuration items need attention"
    else
        log_success "All configurations verified"
    fi
}

# =============================================================================
# Main Execution
# =============================================================================
main() {
    echo ""
    echo "======================================================================"
    echo "  HFT Crypto Bot - System Hardening"
    echo "======================================================================"
    echo ""
    
    check_root
    
    log_warning "This script will modify critical system parameters."
    log_warning "Ensure you understand the implications before proceeding."
    echo ""
    
    read -p "Proceed with hardening? (y/N): " confirm
    if [[ ! "${confirm}" =~ ^[Yy]$ ]]; then
        log_info "Hardening cancelled"
        exit 0
    fi
    
    echo ""
    
    apply_sysctl
    configure_network_interface
    configure_irq_affinity
    verify_configuration
    
    echo ""
    echo "======================================================================"
    echo "  Hardening Complete!"
    echo "======================================================================"
    echo ""
    log_success "System hardening applied successfully"
    echo ""
    log_info "To view current settings:"
    echo "  sysctl -a | grep -E '(tcp_|net.core|vm\\.)'"
    echo ""
    log_info "To revert changes, remove /etc/sysctl.d/99-hft-crypto-bot.conf"
    echo ""
}

main "$@"
