//! Time-Weighted Average Price (TWAP) execution engine.
//! Slices large orders over time to minimize market impact.

use std::sync::atomic::{AtomicF64, AtomicU64, AtomicBool, Ordering};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};
use thiserror::Error;

/// Error types for TWAP execution
#[derive(Debug, Error)]
pub enum TwapError {
    #[error("Invalid duration: must be positive")]
    InvalidDuration,
    #[error("Invalid quantity: must be positive")]
    InvalidQuantity,
    #[error("Order already completed")]
    OrderCompleted,
    #[error("Execution not started")]
    NotStarted,
    #[error("Pre-trade risk check failed: {0}")]
    RiskCheckFailed(String),
}

/// TWAP order state
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TwapState {
    Pending,
    Running,
    Paused,
    Completed,
    Cancelled,
}

/// TWAP execution parameters
#[derive(Debug, Clone)]
pub struct TwapParams {
    pub total_quantity: f64,
    pub duration_secs: u64,
    pub num_slices: usize,
    pub randomize_timing: bool,
    pub min_slice_size: f64,
    pub max_deviation_bps: f64,
}

impl TwapParams {
    /// Create new TWAP parameters with validation
    pub fn new(
        total_quantity: f64,
        duration_secs: u64,
        num_slices: usize,
    ) -> Result<Self, TwapError> {
        if total_quantity <= 0.0 {
            return Err(TwapError::InvalidQuantity);
        }
        if duration_secs == 0 {
            return Err(TwapError::InvalidDuration);
        }
        if num_slices == 0 {
            return Err(TwapError::InvalidQuantity);
        }

        Ok(Self {
            total_quantity,
            duration_secs,
            num_slices,
            randomize_timing: false,
            min_slice_size: total_quantity / num_slices as f64 * 0.5,
            max_deviation_bps: 50.0,
        })
    }

    /// Get slice size
    pub fn slice_size(&self) -> f64 {
        self.total_quantity / self.num_slices as f64
    }

    /// Get interval between slices
    pub fn slice_interval(&self) -> Duration {
        Duration::from_secs(self.duration_secs / self.num_slices as u64)
    }
}

/// Child order generated by TWAP
#[derive(Debug, Clone)]
pub struct TwapChildOrder {
    pub slice_number: usize,
    pub quantity: f64,
    pub target_time: u64,
    pub actual_time: Option<u64>,
    pub filled_quantity: f64,
    pub average_price: f64,
    pub status: ChildOrderStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChildOrderStatus {
    Pending,
    Submitted,
    PartiallyFilled,
    Filled,
    Cancelled,
}

/// TWAP execution engine
pub struct TwapEngine {
    params: TwapParams,
    side: Side,
    state: AtomicU64, // TwapState as u64
    start_time: AtomicU64,
    end_time: AtomicU64,
    executed_quantity: AtomicF64,
    executed_value: AtomicF64,
    current_slice: AtomicU64,
    paused: AtomicBool,
    cancelled: AtomicBool,
    child_orders: crossbeam::queue::SegQueue<TwapChildOrder>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Side {
    Buy,
    Sell,
}

impl TwapEngine {
    /// Create a new TWAP engine
    pub fn new(params: TwapParams, side: Side) -> Self {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        let mut engine = Self {
            params,
            side,
            state: AtomicU64::new(TwapState::Pending as u64),
            start_time: AtomicU64::new(0),
            end_time: AtomicU64::new(0),
            executed_quantity: AtomicF64::new(0.0),
            executed_value: AtomicF64::new(0.0),
            current_slice: AtomicU64::new(0),
            paused: AtomicBool::new(false),
            cancelled: AtomicBool::new(false),
            child_orders: crossbeam::queue::SegQueue::new(),
        };

        // Pre-generate child orders
        engine.initialize_child_orders(now);
        engine
    }

    /// Initialize child orders
    fn initialize_child_orders(&self, start_time: u64) {
        let interval_ms = (self.params.duration_secs * 1000) / self.params.num_slices as u64;

        for i in 0..self.params.num_slices {
            let slice_qty = self.params.slice_size();
            let target_time = start_time + (i as u64 * interval_ms);

            self.child_orders.push(TwapChildOrder {
                slice_number: i,
                quantity: slice_qty,
                target_time,
                actual_time: None,
                filled_quantity: 0.0,
                average_price: 0.0,
                status: ChildOrderStatus::Pending,
            });
        }
    }

    /// Start TWAP execution
    pub fn start(&self) -> Result<(), TwapError> {
        let current_state = self.get_state();
        if current_state != TwapState::Pending {
            return Err(TwapError::NotStarted);
        }

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        self.start_time.store(now, Ordering::Relaxed);
        self.end_time.store(
            now + self.params.duration_secs * 1000,
            Ordering::Relaxed,
        );
        self.state.store(TwapState::Running as u64, Ordering::Relaxed);

        Ok(())
    }

    /// Get next order to execute (if due)
    pub fn get_next_order(&self) -> Option<TwapChildOrder> {
        if self.get_state() != TwapState::Running {
            return None;
        }

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        let current_slice = self.current_slice.load(Ordering::Relaxed) as usize;
        if current_slice >= self.params.num_slices {
            return None;
        }

        // Get the order from queue (we need to track separately)
        let interval_ms = (self.params.duration_secs * 1000) / self.params.num_slices as u64;
        let start = self.start_time.load(Ordering::Relaxed);
        
        if start == 0 {
            return None;
        }

        let target_time = start + (current_slice as u64 * interval_ms);
        
        // Add randomization if enabled
        let actual_target = if self.params.randomize_timing {
            use std::collections::hash_map::DefaultHasher;
            use std::hash::{Hash, Hasher};
            
            let mut hasher = DefaultHasher::new();
            current_slice.hash(&mut hasher);
            let hash = hasher.finish();
            let jitter = (hash % 1000) as i64 - 500; // +/- 500ms
            (target_time as i64 + jitter) as u64
        } else {
            target_time
        };

        if now >= actual_target {
            let slice_qty = self.params.slice_size();
            let order = TwapChildOrder {
                slice_number: current_slice,
                quantity: slice_qty,
                target_time,
                actual_time: Some(now),
                filled_quantity: 0.0,
                average_price: 0.0,
                status: ChildOrderStatus::Submitted,
            };
            
            self.current_slice.fetch_add(1, Ordering::Relaxed);
            Some(order)
        } else {
            None
        }
    }

    /// Report a fill for a child order
    pub fn report_fill(&self, slice_number: usize, quantity: f64, price: f64) -> Result<(), TwapError> {
        if quantity <= 0.0 || price <= 0.0 {
            return Err(TwapError::InvalidQuantity);
        }

        let exec_qty = self.executed_quantity.load(Ordering::Relaxed);
        let exec_val = self.executed_value.load(Ordering::Relaxed);

        self.executed_quantity.store(exec_qty + quantity, Ordering::Relaxed);
        self.executed_value.store(exec_val + quantity * price, Ordering::Relaxed);

        // Check if complete
        if self.executed_quantity.load(Ordering::Relaxed) >= self.params.total_quantity * 0.999 {
            self.state.store(TwapState::Completed as u64, Ordering::Relaxed);
        }

        Ok(())
    }

    /// Pause execution
    pub fn pause(&self) {
        if self.get_state() == TwapState::Running {
            self.paused.store(true, Ordering::Relaxed);
            self.state.store(TwapState::Paused as u64, Ordering::Relaxed);
        }
    }

    /// Resume execution
    pub fn resume(&self) {
        if self.get_state() == TwapState::Paused && !self.cancelled.load(Ordering::Relaxed) {
            self.paused.store(false, Ordering::Relaxed);
            self.state.store(TwapState::Running as u64, Ordering::Relaxed);
        }
    }

    /// Cancel execution
    pub fn cancel(&self) {
        self.cancelled.store(true, Ordering::Relaxed);
        self.state.store(TwapState::Cancelled as u64, Ordering::Relaxed);
    }

    /// Get current state
    pub fn get_state(&self) -> TwapState {
        match self.state.load(Ordering::Relaxed) {
            0 => TwapState::Pending,
            1 => TwapState::Running,
            2 => TwapState::Paused,
            3 => TwapState::Completed,
            4 => TwapState::Cancelled,
            _ => TwapState::Pending,
        }
    }

    /// Get execution progress
    pub fn get_progress(&self) -> TwapProgress {
        let executed_qty = self.executed_quantity.load(Ordering::Relaxed);
        let executed_val = self.executed_value.load(Ordering::Relaxed);
        let current_slice = self.current_slice.load(Ordering::Relaxed);

        TwapProgress {
            executed_quantity: executed_qty,
            executed_value: executed_val,
            remaining_quantity: (self.params.total_quantity - executed_qty).max(0.0),
            average_price: if executed_qty > 0.0 {
                executed_val / executed_qty
            } else {
                0.0
            },
            progress_percent: executed_qty / self.params.total_quantity * 100.0,
            slices_completed: current_slice as usize,
            total_slices: self.params.num_slices,
        }
    }

    /// Get TWAP parameters
    pub fn params(&self) -> &TwapParams {
        &self.params
    }

    /// Get side
    pub fn side(&self) -> Side {
        self.side
    }

    /// Check if execution is complete
    pub fn is_complete(&self) -> bool {
        self.get_state() == TwapState::Completed
    }

    /// Get time remaining in milliseconds
    pub fn time_remaining_ms(&self) -> i64 {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;
        let end = self.end_time.load(Ordering::Relaxed);
        
        if end == 0 {
            return self.params.duration_secs as i64 * 1000;
        }
        
        end as i64 - now as i64
    }
}

/// TWAP execution progress
#[derive(Debug, Clone, Copy)]
pub struct TwapProgress {
    pub executed_quantity: f64,
    pub executed_value: f64,
    pub remaining_quantity: f64,
    pub average_price: f64,
    pub progress_percent: f64,
    pub slices_completed: usize,
    pub total_slices: usize,
}

impl TwapProgress {
    /// Check if behind schedule
    pub fn is_behind_schedule(&self) -> bool {
        let expected_progress = self.slices_completed as f64 / self.total_slices as f64 * 100.0;
        self.progress_percent < expected_progress * 0.9
    }

    /// Check if ahead of schedule
    pub fn is_ahead_of_schedule(&self) -> bool {
        let expected_progress = self.slices_completed as f64 / self.total_slices as f64 * 100.0;
        self.progress_percent > expected_progress * 1.1
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_twap_params() {
        let params = TwapParams::new(1000.0, 3600, 10).unwrap();
        
        assert_eq!(params.slice_size(), 100.0);
        assert_eq!(params.slice_interval(), Duration::from_secs(360));
    }

    #[test]
    fn test_twap_engine() {
        let params = TwapParams::new(1000.0, 60, 5).unwrap();
        let engine = TwapEngine::new(params, Side::Buy);
        
        assert_eq!(engine.get_state(), TwapState::Pending);
        
        engine.start().unwrap();
        assert_eq!(engine.get_state(), TwapState::Running);
        
        // Simulate time passing and get orders
        std::thread::sleep(Duration::from_millis(100));
        let order = engine.get_next_order();
        assert!(order.is_some());
        
        // Report fill
        if let Some(o) = order {
            engine.report_fill(o.slice_number, o.quantity, 100.0).unwrap();
        }
        
        let progress = engine.get_progress();
        assert!(progress.executed_quantity > 0.0);
    }

    #[test]
    fn test_twap_pause_resume() {
        let params = TwapParams::new(1000.0, 60, 5).unwrap();
        let engine = TwapEngine::new(params, Side::Sell);
        
        engine.start().unwrap();
        assert_eq!(engine.get_state(), TwapState::Running);
        
        engine.pause();
        assert_eq!(engine.get_state(), TwapState::Paused);
        
        engine.resume();
        assert_eq!(engine.get_state(), TwapState::Running);
    }

    #[test]
    fn test_twap_cancel() {
        let params = TwapParams::new(1000.0, 60, 5).unwrap();
        let engine = TwapEngine::new(params, Side::Buy);
        
        engine.start().unwrap();
        engine.cancel();
        
        assert_eq!(engine.get_state(), TwapState::Cancelled);
        assert!(engine.get_next_order().is_none());
    }

    #[test]
    fn test_progress_tracking() {
        let params = TwapParams::new(1000.0, 60, 10).unwrap();
        let engine = TwapEngine::new(params, Side::Buy);
        
        engine.start().unwrap();
        
        // Fill half the order
        for i in 0..5 {
            engine.report_fill(i, 100.0, 100.0).unwrap();
        }
        
        let progress = engine.get_progress();
        assert!((progress.progress_percent - 50.0).abs() < 1.0);
        assert_eq!(progress.remaining_quantity, 500.0);
    }
}
