//! Backtest Metrics Module Root
//! 
//! This module manages the continuous stream of performance analytics to the UI
//! and SOUL.md for ML backend evaluation.

pub mod sharpe_sortino;
pub mod expectancy;

// Re-export main types for convenience
pub use sharpe_sortino::{
    OnlineCalmarCalculator, OnlineDrawdownTracker, OnlineSharpeCalculator,
    OnlineSortinoCalculator, RiskMetricsAggregator, RiskMetricsSnapshot,
    RiskMetricsStats,
};

pub use expectancy::{
    ExpectancyCalculator, ExpectancySnapshot, SymbolExpectancyTracker, TradeResult,
};

/// Combined metrics aggregator for complete backtest analysis
pub struct BacktestMetricsAggregator {
    /// Risk metrics (Sharpe, Sortino, Calmar)
    risk_metrics: RiskMetricsAggregator,
    /// Trade expectancy metrics
    expectancy: ExpectancyCalculator,
    /// Per-symbol tracking
    symbol_tracker: SymbolExpectancyTracker,
    /// Total trades counter
    total_trades: std::sync::atomic::AtomicUsize,
}

impl BacktestMetricsAggregator {
    pub fn new(
        annualization_factor: f64,
        risk_free_rate: f64,
        target_return: f64,
    ) -> Self {
        Self {
            risk_metrics: RiskMetricsAggregator::new(annualization_factor, risk_free_rate, target_return),
            expectancy: ExpectancyCalculator::new(),
            symbol_tracker: SymbolExpectancyTracker::new(),
            total_trades: std::sync::atomic::AtomicUsize::new(0),
        }
    }
    
    /// Record a completed trade
    pub fn record_trade(&self, trade: &TradeResult) {
        self.total_trades.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        
        // Update expectancy calculator
        self.expectancy.record_trade(trade);
        
        // Update per-symbol tracker
        self.symbol_tracker.record_trade(&trade.symbol, trade);
        
        // Update risk metrics with return percentage
        if trade.pnl_pct != 0.0 {
            self.risk_metrics.update(trade.pnl_pct / 100.0);
        }
    }
    
    /// Get combined metrics snapshot
    pub fn snapshot(&self) -> BacktestMetricsSnapshot {
        BacktestMetricsSnapshot {
            risk_metrics: self.risk_metrics.snapshot(),
            expectancy: self.expectancy.snapshot(),
            total_trades: self.total_trades.load(std::sync::atomic::Ordering::Relaxed),
        }
    }
    
    /// Export full report in SOUL.md format
    pub fn to_soul_md(&self) -> String {
        let snap = self.snapshot();
        
        format!(
            r#"# Backtest Performance Report

## Risk-Adjusted Returns

| Metric | Value |
|--------|-------|
| Sharpe Ratio | {:.4} |
| Sortino Ratio | {:.4} |
| Calmar Ratio | {:.4} |
| Max Drawdown | {:.2}% |
| Annualized Return | {:.2}% |
| Annualized Volatility | {:.2}% |
| Downside Deviation | {:.2}% |

{}

## Summary Statistics

- **Total Trades**: {}
- **Observation Count**: {}
- **Profit Factor**: {:.2}
- **Expectancy**: ${:.2}

---
*Generated by HFT System - Stage 19*
"#,
            snap.risk_metrics.sharpe,
            snap.risk_metrics.sortino,
            snap.risk_metrics.calmar,
            snap.risk_metrics.max_drawdown * 100.0,
            snap.risk_metrics.annualized_return * 100.0,
            snap.risk_metrics.annualized_volatility * 100.0,
            snap.risk_metrics.downside_deviation * 100.0,
            self.expectancy.to_soul_md(),
            snap.total_trades,
            snap.risk_metrics.observation_count,
            snap.expectancy.profit_factor,
            snap.expectancy.expectancy,
        )
    }
    
    /// Reset all metrics
    pub fn reset(&self) {
        self.risk_metrics.reset();
        self.expectancy.reset();
        self.total_trades.store(0, std::sync::atomic::Ordering::Relaxed);
    }
    
    /// Get risk metrics reference
    pub fn risk_metrics(&self) -> &RiskMetricsAggregator {
        &self.risk_metrics
    }
    
    /// Get expectancy reference
    pub fn expectancy(&self) -> &ExpectancyCalculator {
        &self.expectancy
    }
}

#[derive(Debug, Clone)]
pub struct BacktestMetricsSnapshot {
    pub risk_metrics: RiskMetricsSnapshot,
    pub expectancy: ExpectancySnapshot,
    pub total_trades: usize,
}

/// UI dashboard update payload
#[derive(Debug, Clone)]
pub struct DashboardUpdate {
    /// Current Sharpe ratio
    pub sharpe: f64,
    /// Current Sortino ratio
    pub sortino: f64,
    /// Current Calmar ratio
    pub calmar: f64,
    /// Win rate percentage
    pub win_rate: f64,
    /// Profit factor
    pub profit_factor: f64,
    /// Total PnL
    pub total_pnl: f64,
    /// Max drawdown percentage
    pub max_drawdown: f64,
    /// Trade count
    pub trade_count: usize,
    /// Timestamp
    pub timestamp_ns: u64,
}

impl From<&BacktestMetricsSnapshot> for DashboardUpdate {
    fn from(snap: &BacktestMetricsSnapshot) -> Self {
        Self {
            sharpe: snap.risk_metrics.sharpe,
            sortino: snap.risk_metrics.sortino,
            calmar: snap.risk_metrics.calmar,
            win_rate: snap.expectancy.win_rate * 100.0,
            profit_factor: snap.expectancy.profit_factor,
            total_pnl: snap.expectancy.total_pnl,
            max_drawdown: snap.risk_metrics.max_drawdown * 100.0,
            trade_count: snap.total_trades,
            timestamp_ns: current_timestamp_ns(),
        }
    }
}

fn current_timestamp_ns() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos() as u64
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;
    
    #[test]
    fn test_backtest_aggregator() {
        let agg = BacktestMetricsAggregator::new(252.0_f64.sqrt(), 0.0, 0.0);
        
        // Simulate some trades
        for i in 0..10 {
            let side = if i % 2 == 0 { 1 } else { -1 };
            let exit_price = if i % 3 == 0 { 49900.0 } else { 50100.0 };
            
            let trade = TradeResult::new(
                format!("T{}", i),
                "BTCUSDT".to_string(),
                side,
                50000.0,
                exit_price,
                1.0,
                Duration::from_secs(3600),
            );
            
            agg.record_trade(&trade);
        }
        
        let snap = agg.snapshot();
        assert_eq!(snap.total_trades, 10);
        assert!(snap.risk_metrics.observation_count > 0);
    }
    
    #[test]
    fn test_dashboard_update() {
        let agg = BacktestMetricsAggregator::new(252.0_f64.sqrt(), 0.0, 0.0);
        
        let trade = TradeResult::new(
            "T1".to_string(),
            "BTCUSDT".to_string(),
            1,
            50000.0,
            50500.0,
            1.0,
            Duration::from_secs(3600),
        );
        agg.record_trade(&trade);
        
        let snap = agg.snapshot();
        let update: DashboardUpdate = (&snap).into();
        
        assert!((update.win_rate - 100.0).abs() < 0.01);
        assert!(update.trade_count == 1);
    }
    
    #[test]
    fn test_soul_md_export() {
        let agg = BacktestMetricsAggregator::new(252.0_f64.sqrt(), 0.0, 0.0);
        
        let trade = TradeResult::new(
            "T1".to_string(),
            "BTCUSDT".to_string(),
            1,
            50000.0,
            51000.0,
            1.0,
            Duration::from_secs(3600),
        );
        agg.record_trade(&trade);
        
        let md = agg.to_soul_md();
        assert!(md.contains("Backtest Performance Report"));
        assert!(md.contains("Sharpe Ratio"));
        assert!(md.contains("Trade Expectancy Metrics"));
    }
}
